# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App Store App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for App Store App
  pod 'Alamofire', '4.8.0'
  pod 'SwiftyJSON', '3.1.4'
  pod 'SDWebImage'
end
